[versions]

#...

workRuntimeKts = "2.9.1"
okhttp = '4.11.0'
appcompat = "1.7.0"
material = "1.12.0"
kotlin = "1.9.22"
constraintlayout = "2.2.0"

[libraries]

androidx-work-runtime-ktx = { group = 'androidx.work', name = 'work-runtime-ktx', version.ref = 'workRuntimeKts' }
okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp' }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }