[versions]

#...

workRuntimeKts = "2.9.1"
okhttp = '4.11.0'

[libraries]

androidx-work-runtime-ktx = { group = 'androidx.work', name = 'work-runtime-ktx', version.ref = 'workRuntimeKts' }
okhttp = { module = 'com.squareup.okhttp3:ok', version.ref = 'okhttp' }